#!/bin/bash
# Script to destroy and remove VMs completely
# useful for testing :)

if [ -z $1 ]; then
    # Requires a VM name to destroy/undefine
    echo "$0: $VM_NAME"
else
    VM_NAME=$1
fi

# remove VM from virt-manager
sudo virsh destroy $VM_NAME
sudo virsh undefine $VM_NAME

# remove entry from /etc/hosts
HOST_ENTRY=$(grep $VM_NAME /etc/hosts)

if [[ $(echo "$HOST_ENTRY" | wc -l) -gt 1 ]]; then
    echo "More than one /etc/hosts entry for $VM_NAME:"
    echo "$HOST_ENTRY"
    exit 1
elif [[ $(echo "$HOST_ENTRY" | wc -l) -eq 0 ]]; then
    echo "No /etc/hosts entry for $VM_NAME"
else
    sudo sed -i "s/$HOST_ENTRY//g" /etc/hosts
    echo "$VM_NAME entry removed from /etc/hosts"
fi
